"use strict";
//makes an array for the events of each day
let dayEvent = new Array();

dayEvent[1] = "<br>";
dayEvent[2] = "<br> Showing @ 6:00";
dayEvent[3] = "<br>";
dayEvent[4] = "<br>";
dayEvent[5] = "<br>";
dayEvent[6] = "<br>";
dayEvent[7] = "<br>";
dayEvent[8] = "<br>";
dayEvent[9] = "<br> Showing @ 6:00";
dayEvent[10] = "<br>";
dayEvent[11] = "<br>";
dayEvent[12] = "<br>";
dayEvent[13] = "<br>";
dayEvent[14] = "<br>";
dayEvent[15] = "<br>";
dayEvent[16] = "<br> Showing @ 6:00";
dayEvent[17] = "<br>";
dayEvent[18] = "<br>";
dayEvent[19] = "<br>";
dayEvent[20] = "<br>";
dayEvent[21] = "<br>";
dayEvent[22] = "<br>";
dayEvent[23] = "<br> Showing @ 6:00";
dayEvent[24] = "<br> Holographic Pop-idol @ 6:00 PM";
dayEvent[25] = "<br>";
dayEvent[26] = "<br>";
dayEvent[27] = "<br>";
dayEvent[28] = "<br>";
dayEvent[29] = "<br>";
dayEvent[30] = "<br> Showing @ 6:00";
dayEvent[31] = "<br>";
